// <auto-generated />
using System;
using Livestreaming.Infrastructure.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Livestreaming.Infrastructure.ORM.Migrations.Livestreaming
{
    [DbContext(typeof(LivestreamContext))]
    [Migration("20220522110309_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Livestreaming.Domain.Models.LivestreamProperties", b =>
                {
                    b.Property<string>("LivestreamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArchiveStreamingLocatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DrvAssetFilterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrvStreamingLocatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncodingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiveEventName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LiveOutputName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LiveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordingDuration")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreamingEndpointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreamingLocatorName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("StreamingProtocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LivestreamId");

                    b.ToTable("Livestreams");
                });

            modelBuilder.Entity("Livestreaming.Domain.Models.LivestreamProperties", b =>
                {
                    b.OwnsOne("Livestreaming.Domain.Models.LivestreamEndpoints", "RunningEndpoints", b1 =>
                        {
                            b1.Property<string>("LivestreamPropertiesLivestreamId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("DashManifest")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DashManifest");

                            b1.Property<string>("HlsManifest")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HlsManifest");

                            b1.Property<string>("IngestUrl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("IngestUrl");

                            b1.Property<string>("PreviewUrl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PreviewUrl");

                            b1.HasKey("LivestreamPropertiesLivestreamId");

                            b1.ToTable("Livestreams");

                            b1.WithOwner()
                                .HasForeignKey("LivestreamPropertiesLivestreamId");
                        });

                    b.OwnsOne("Livestreaming.Domain.Models.LivestreamPlaybackEndpoints", "PlaybackEndpoints", b1 =>
                        {
                            b1.Property<string>("LivestreamPropertiesLivestreamId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("DashManifest")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DashManifest");

                            b1.Property<string>("HlsManifest")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HlsManifest");

                            b1.HasKey("LivestreamPropertiesLivestreamId");

                            b1.ToTable("Livestreams");

                            b1.WithOwner()
                                .HasForeignKey("LivestreamPropertiesLivestreamId");
                        });

                    b.Navigation("PlaybackEndpoints")
                        .IsRequired();

                    b.Navigation("RunningEndpoints")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
